config/routes.rb
WickedScience::Application.routes.draw do

  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'

  resources :users
  resources :sessions

  resources :articles
  resources :comments, :except => :edit

  root :to => 'articles#index'

  
  

end

app/models/article.rb
class Article < ActiveRecord::Base
  has_many :comments

  attr_accessible :title, :author, :link

  validates :title, :author, :link, :presence => true



end

app/models/comment.rb
class Comment < ActiveRecord::Base
   belongs_to :article
  # has_many :comments, as :commentable

  attr_accessible :text, :article_id

  validates :text, :article_id, :presence => true





end

app/models/user.rb
class User < ActiveRecord::Base

  has_secure_password

  attr_accessible :email, :password, :password_confirmation

  validates :email, :password, :password_confirmation, :presence => true

  validates :email, :uniqueness => true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  
  protect_from_forgery

  private

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user

  def authorize
    redirect_to login_url, alert: "Please log in or sign up for a new account to access this site" if current_user.nil?
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_filter :authorize #, only: [:edit, :update]
  
  def new
    @article = Article.new
  end

  def create
    @article = Article.new(params[:article])
    
    if @article.save
      flash[:notice] = "Your article was successfully created."
      redirect_to action: "index"
    else 
      render :new
      flash[:alert] = "YOU BLEW IT!"
    end
  end

  def index
    @articles = Article.all
  end

  def update
    @article = Article.find(params[:id])

    if @article.update_attributes(params[:article])
      redirect_to action: "index"
      flash[:notice] = "Your article was successfully updated."
    else
      render :edit
      flash[:alert] = "YOU BLEW IT!"
    end
  end

  def edit
    @article = Article.find(params[:id])
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy
    flash[:notice] = "Your article was obliterated!  I hope you are happy."
    redirect_to action: "index"
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def new
    @comment = Comment.new
  end

  def create
    @comment = Comment.new(params[:comment])
    
    if @comment.save
      flash[:notice] = "Your comment was successfully added."
      redirect_to action: "new"
    else 
      render :new
      flash[:alert] = "No comment for you!"
    end
  end


end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by_email(params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_url, :notice => "Logged in!"
    else
      flash.now.alert = "Invalid email or password"
      render "new"
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, :notice => "Logged out!"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(params[:user])
    if @user.save
      session[:user_id] = @user.id
      redirect_to action: "index", :notice => "Signed up!"
    else
      render "new"
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/articles/_form.html.erb
<% if @article.errors.any? %>
  <div class="alert alert-error">
    <h3>Loser!  How hard is it to fill in ALL the blanks?</h3>
    <ul>
      <% @article.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    <ul>
  </div>
<% end %>    



<%= form_for @article do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.label :author %>
  <%= f.text_field :author %>
  <%= f.label :link %>
  <%= f.text_field :link %>
  <%= f.submit :class => 'btn btn-primary' %>
<% end %>

app/views/articles/edit.html.erb
<% provide :title, "Edit #{@article.title}" %>

<h1><%= yield :title %></h1>

<%= render 'form' %>

app/views/articles/index.html.erb
<% provide :title, 'Home' %>

<h1>Wicked Science News</h1>

<h2>A user contributed collection of interesting science stories</h2>

<table class="table">
  <tr>
    <td>Title</td>
    <td>Author</td>
    <td>Link</td>
    <td></td>
    <td></td>
  </tr>
  <% @articles.each do |article| %>
    <tr>
      <td><%= article.title %></td>
      <td><%= article.author %></td>
      <td><%= article.link %></td>
      <td><%= link_to 'Comment', new_comment_path, :class => 'btn btn-primary' %></td>
      <td><%= link_to 'Edit', edit_article_path(article), :class => 'btn btn-primary' %></td>
      <td><%= link_to 'Delete', article, :class => 'btn btn-primary', :method => :delete, :data => { :confirm => 'Are you sure?' } %></td>
    </tr>
  <% end %>
</table>

<p><%= link_to 'Add article', new_article_path, :class => 'btn btn-primary' %></p>

app/views/articles/new.html.erb
<% provide :title, "New Article" %>

<h1><%= yield :title %></h1>

<%= render 'form' %>

app/views/comments/new.html.erb
<% provide :title, 'Comments' %>

<h1>Wicked Science News</h1>

<h2>@article.title</h2>
<h3>@article.author</h3>

<%= @comment.label :text %>
<%= @comment.text_field :text %>
<%= f.submit :class => 'btn btn-primary' %>

app/views/layouts/application.html.erb
<head>
  <title>WickedScience | <%= yield :title %></title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>

  <% if current_user %>
    Logged in as <%= current_user.email %>.
    <%= link_to "Log Out", logout_path %>
  <% else %>
    <%= link_to "Sign Up", signup_path %> or
    <%= link_to "Log In", login_path %>
  <% end %>
</head>

<body>
  <div class="container">
    <% if flash[:notice] %>
      <div class="alert alert-info"><%= flash[:notice] %></div>
    <% end %>
    <% if flash[:alert] %>
      <div class_"alert alert-error"><%= flash[:alert] %></div>
    <% end %>

    <%= yield %>
  </div>
</body>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<%= form_for @user do |f| %>
  <% if @user.errors.any? %>
    <div class="error_messages">
      <h2>Form is invalid</h2>
      <ul>
        <% @user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="actions"><%= f.submit "Sign Up" %></div>
<% end %>